version: '3.1'

services:
  jrtb-bot:
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
    depends_on:
      - jrtb-db

  jrtb-db:
    image: mysql:5.7
    restart: always
    container_name: dev-jrtb-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "jrtb_db"
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"