version: '3.1'

services:
  jrtb-db:
    image: mysql:5.7
    restart: always
    container_name: dev-jrtb-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "dev_jrtb_db"
      MYSQL_USER: "bestuser"
      MYSQL_PASSWORD: "bestuser"
      MYSQL_ROOT_PASSWORD: "root"